name: env_reader
description: Read, encrypt, or generate environment variables from a .env file into an obfuscated Dart model.
version: 1.8.0
homepage: https://github.com/Nialixus/env_reader.git
funding: 
  - https://www.buymeacoffee.com/nialixus
screenshots:
  - description: 'Env Reader Logo'
    path: logo.png
topics:
  - utility
  - env

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  args: ^2.4.2
  encryptor: ^0.0.1
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter: null