name: env_reader
description: Elevate your .env configuration's integrity by encrypting and decrypting from diverse sources across various platforms plus with additional auto generation into dart model.
version: 1.1.0
homepage: https://github.com/Nialixus/env_reader.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  args: ^2.4.2
  encryptor: ^0.0.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  universal_file: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter: null