name: env_reader
description: Read, encrypt, or generate environment variables from a .env file
  into an obfuscated Dart model.
version: 2.1.0
homepage: https://github.com/Nialixus/env_reader
repository: https://github.com/Nialixus/env_reader.git
issue_tracker: https://github.com/Nialixus/env_reader/issues
executables:
  env_reader: env_reader
funding:
  - https://www.buymeacoffee.com/nialixus
screenshots:
  - description: 'Env Reader Logo'
    path: logo.png
topics:
  - utility
  - env
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  args: ^2.4.2
  cryptography: ^2.2.0
  http: ^1.1.0

dev_dependencies:
